<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\EventTheme;

class EventThemeSeeder extends Seeder
{
    public function run(): void
    {
        $themes = [

            // ─── STEMAN & LOKAL (Prioritas tertinggi) ───────────────────────
            [
                'name'            => 'HUT STEMAN',
                'description'     => 'Hari Ulang Tahun Forum Silaturahmi Alumni STEMAN',
                'start_month'     => 11, 'start_day' => 1,
                'end_month'       => 11, 'end_day'   => 30,
                'primary_color'   => '#ffcc00',
                'secondary_color' => '#000000',
                'accent_color'    => '#ff6600',
                'css_class'       => 'theme-hut-steman',
                'banner_text'     => 'Selamat Ulang Tahun STEMAN! 🎉',
                'banner_subtext'  => 'Bersatu, Berkarya, Berprestasi – Alumni SMKN 2 Ternate',
                'banner_icon'     => 'bi bi-mortarboard-fill',
                'emoji'           => '🎓',
                'show_countdown'  => false,
                'priority'        => 100,
                'is_active'       => true,
            ],
            [
                'name'            => 'Ulang Tahun Admin',
                'description'     => 'Hari Ulang Tahun Admin Portal (11 Oktober)',
                'start_month'     => 10, 'start_day' => 11,
                'end_month'       => 10, 'end_day'   => 11,
                'primary_color'   => '#e91e8c',
                'secondary_color' => '#7c3aed',
                'accent_color'    => '#fbbf24',
                'css_class'       => 'theme-birthday-admin',
                'banner_text'     => '🎂 Selamat Ulang Tahun, Admin!',
                'banner_subtext'  => 'Terima kasih telah berdedikasi untuk Portal Alumni STEMAN ❤️',
                'banner_icon'     => 'bi bi-gift-fill',
                'emoji'           => '🎂',
                'show_countdown'  => false,
                'priority'        => 95,
                'is_active'       => true,
            ],
            [
                'name'            => 'HUT Provinsi Maluku Utara',
                'description'     => 'Hari Ulang Tahun Provinsi Maluku Utara – 12 Oktober',
                'start_month'     => 10, 'start_day' => 10,
                'end_month'       => 10, 'end_day'   => 14,
                'primary_color'   => '#1a6b3a',
                'secondary_color' => '#c0392b',
                'accent_color'    => '#f39c12',
                'css_class'       => 'theme-hut-malut',
                'banner_text'     => 'Selamat HUT Provinsi Maluku Utara!',
                'banner_subtext'  => 'Diperingati setiap 12 Oktober – Semangat Maluku Utara Maju!',
                'banner_icon'     => 'bi bi-map-fill',
                'emoji'           => '🏝️',
                'show_countdown'  => false,
                'priority'        => 90,
                'is_active'       => true,
            ],
            [
                'name'            => 'HUT Pemerintah Kota Ternate',
                'description'     => 'HUT Pemerintah Kota Ternate – 27 April',
                'start_month'     => 4, 'start_day' => 25,
                'end_month'       => 4, 'end_day'   => 29,
                'primary_color'   => '#0d6efd',
                'secondary_color' => '#198754',
                'accent_color'    => '#ffc107',
                'css_class'       => 'theme-hut-ternate',
                'banner_text'     => 'Selamat HUT Pemerintah Kota Ternate!',
                'banner_subtext'  => 'Diperingati setiap 27 April – Kota Ternate Bergerak Maju',
                'banner_icon'     => 'bi bi-buildings-fill',
                'emoji'           => '🏙️',
                'show_countdown'  => false,
                'priority'        => 88,
                'is_active'       => true,
            ],
            [
                'name'            => 'HAJAT Ternate',
                'description'     => 'Hari Jadi Ternate – 29 Desember',
                'start_month'     => 12, 'start_day' => 27,
                'end_month'       => 12, 'end_day'   => 31,
                'primary_color'   => '#7b2d8b',
                'secondary_color' => '#f39c12',
                'accent_color'    => '#e74c3c',
                'css_class'       => 'theme-hajat-ternate',
                'banner_text'     => 'Selamat Hari Jadi Ternate (HAJAT)!',
                'banner_subtext'  => 'Diperingati setiap 29 Desember – Ternate Kota Rempah Dunia',
                'banner_icon'     => 'bi bi-star-fill',
                'emoji'           => '⭐',
                'show_countdown'  => false,
                'priority'        => 88,
                'is_active'       => true,
            ],

            // ─── NASIONAL (Prioritas tinggi) ────────────────────────────────
            [
                'name'            => 'HUT Kemerdekaan RI',
                'description'     => 'Hari Ulang Tahun Kemerdekaan Republik Indonesia – 17 Agustus',
                'start_month'     => 8, 'start_day' => 1,
                'end_month'       => 8, 'end_day'   => 31,
                'primary_color'   => '#dc3545',
                'secondary_color' => '#ffffff',
                'accent_color'    => '#dc3545',
                'css_class'       => 'theme-kemerdekaan',
                'banner_text'     => '🇮🇩 Dirgahayu Republik Indonesia!',
                'banner_subtext'  => 'Merdeka! Alumni STEMAN siap berkontribusi untuk bangsa dan negara.',
                'banner_icon'     => 'bi bi-flag-fill',
                'emoji'           => '🇮🇩',
                'show_countdown'  => true,
                'countdown_month' => 8,
                'countdown_day'   => 17,
                'countdown_label' => 'Menuju 17 Agustus',
                'priority'        => 80,
                'is_active'       => true,
            ],
            [
                'name'            => 'Hari Pahlawan',
                'description'     => 'Hari Pahlawan Nasional – 10 November',
                'start_month'     => 11, 'start_day' => 9,
                'end_month'       => 11, 'end_day'   => 11,
                'primary_color'   => '#7b341e',
                'secondary_color' => '#f6ad55',
                'accent_color'    => '#e53e3e',
                'css_class'       => 'theme-pahlawan',
                'banner_text'     => 'Selamat Hari Pahlawan! 🦅',
                'banner_subtext'  => '10 November – Berjuang dalam Kebaikan adalah Semangat Pahlawan',
                'banner_icon'     => 'bi bi-shield-fill',
                'emoji'           => '🦅',
                'show_countdown'  => false,
                'priority'        => 75,
                'is_active'       => true,
            ],
            [
                'name'            => 'Hari Sumpah Pemuda',
                'description'     => 'Hari Sumpah Pemuda – 28 Oktober',
                'start_month'     => 10, 'start_day' => 27,
                'end_month'       => 10, 'end_day'   => 29,
                'primary_color'   => '#1a56db',
                'secondary_color' => '#e74c3c',
                'accent_color'    => '#ffffff',
                'css_class'       => 'theme-sumpah-pemuda',
                'banner_text'     => 'Selamat Hari Sumpah Pemuda!',
                'banner_subtext'  => '28 Oktober – Satu Nusa, Satu Bangsa, Satu Bahasa Indonesia',
                'banner_icon'     => 'bi bi-people-fill',
                'emoji'           => '✊',
                'show_countdown'  => false,
                'priority'        => 73,
                'is_active'       => true,
            ],
            [
                'name'            => 'Hari Lahir Pancasila',
                'description'     => 'Hari Lahir Pancasila – 1 Juni',
                'start_month'     => 6, 'start_day' => 1,
                'end_month'       => 6, 'end_day'   => 2,
                'primary_color'   => '#dc3545',
                'secondary_color' => '#ffc107',
                'accent_color'    => '#198754',
                'css_class'       => 'theme-pancasila',
                'banner_text'     => 'Selamat Hari Lahir Pancasila!',
                'banner_subtext'  => '1 Juni – Pancasila: Dasar Negara & Pandangan Hidup Bangsa',
                'banner_icon'     => 'bi bi-star-fill',
                'emoji'           => '⭐',
                'show_countdown'  => false,
                'priority'        => 72,
                'is_active'       => true,
            ],
            [
                'name'            => 'Hari Kebangkitan Nasional',
                'description'     => 'Hari Kebangkitan Nasional – 20 Mei',
                'start_month'     => 5, 'start_day' => 19,
                'end_month'       => 5, 'end_day'   => 21,
                'primary_color'   => '#198754',
                'secondary_color' => '#ffffff',
                'accent_color'    => '#ffc107',
                'css_class'       => 'theme-harkitnas',
                'banner_text'     => 'Selamat Hari Kebangkitan Nasional!',
                'banner_subtext'  => '20 Mei – Bangkit & Bergerak Maju Bersama Alumni STEMAN',
                'banner_icon'     => 'bi bi-arrow-up-circle-fill',
                'emoji'           => '🌟',
                'show_countdown'  => false,
                'priority'        => 70,
                'is_active'       => true,
            ],
            [
                'name'            => 'Tahun Baru',
                'description'     => 'Selamat Tahun Baru Masehi',
                'start_month'     => 1, 'start_day' => 1,
                'end_month'       => 1, 'end_day'   => 3,
                'primary_color'   => '#7c3aed',
                'secondary_color' => '#f59e0b',
                'accent_color'    => '#ec4899',
                'css_class'       => 'theme-tahun-baru',
                'banner_text'     => '🎆 Selamat Tahun Baru!',
                'banner_subtext'  => 'Semoga tahun baru membawa keberkahan bagi seluruh keluarga besar Alumni STEMAN',
                'banner_icon'     => 'bi bi-stars',
                'emoji'           => '🎆',
                'show_countdown'  => false,
                'priority'        => 65,
                'is_active'       => true,
            ],
            [
                'name'            => 'Hari Natal',
                'description'     => 'Peringatan Hari Natal – 25 Desember',
                'start_month'     => 12, 'start_day' => 24,
                'end_month'       => 12, 'end_day'   => 26,
                'primary_color'   => '#166534',
                'secondary_color' => '#dc2626',
                'accent_color'    => '#fbbf24',
                'css_class'       => 'theme-natal',
                'banner_text'     => '🎄 Selamat Hari Natal!',
                'banner_subtext'  => 'Damai dan kebahagiaan untuk seluruh Alumni STEMAN yang merayakan',
                'banner_icon'     => 'bi bi-tree-fill',
                'emoji'           => '🎄',
                'show_countdown'  => false,
                'priority'        => 65,
                'is_active'       => true,
            ],
            [
                'name'            => 'Hari Buruh',
                'description'     => 'Hari Buruh Internasional – 1 Mei',
                'start_month'     => 5, 'start_day' => 1,
                'end_month'       => 5, 'end_day'   => 1,
                'primary_color'   => '#dc2626',
                'secondary_color' => '#ffffff',
                'accent_color'    => '#fbbf24',
                'css_class'       => 'theme-hari-buruh',
                'banner_text'     => 'Selamat Hari Buruh Internasional!',
                'banner_subtext'  => '1 Mei – Semangat dan kerja keras Alumni STEMAN untuk Indonesia',
                'banner_icon'     => 'bi bi-hammer',
                'emoji'           => '✊',
                'show_countdown'  => false,
                'priority'        => 60,
                'is_active'       => true,
            ],

            // ─── HARI BESAR ISLAM (tanggal mengikuti kalender Hijriah) ─────────
            // Diperbarui otomatis setiap tahun via: php artisan event-themes:sync-islamic
            // Tanggal berikut sudah dikalibrasi untuk tahun Masehi 2026.

            [
                'name'            => 'Isra Mi\'raj',
                'description'     => 'Isra Mi\'raj Nabi Muhammad SAW – 27 Rajab 1447 H',
                'start_month'     => 1, 'start_day' => 16,
                'end_month'       => 1, 'end_day'   => 18,
                'primary_color'   => '#1a4a7a',
                'secondary_color' => '#f0c040',
                'accent_color'    => '#ffffff',
                'css_class'       => 'theme-isra-miraj',
                'banner_text'     => '🌙 Selamat Memperingati Isra Mi\'raj 1447 H',
                'banner_subtext'  => '27 Rajab – Perjalanan Agung Nabi Muhammad SAW',
                'banner_icon'     => 'bi bi-moon-stars-fill',
                'emoji'           => '🌙',
                'show_countdown'  => false,
                'priority'        => 87,
                'is_active'       => true,
                'is_islamic'      => true,
                'hijri_month'     => 7,
                'hijri_day'       => 27,
                'hijri_duration'  => 3,
            ],
            [
                'name'            => 'Bulan Ramadan',
                'description'     => 'Bulan Suci Ramadan 1447 H',
                'start_month'     => 2, 'start_day' => 18,
                'end_month'       => 3, 'end_day'   => 19,
                'primary_color'   => '#1a3a5c',
                'secondary_color' => '#c8a84b',
                'accent_color'    => '#f9f3e3',
                'css_class'       => 'theme-ramadan',
                'banner_text'     => '🌙 Selamat Menunaikan Ibadah Puasa Ramadan 1447 H',
                'banner_subtext'  => 'Marhaban Ya Ramadan – Semoga amal ibadah kita diterima Allah SWT',
                'banner_icon'     => 'bi bi-moon-fill',
                'emoji'           => '🌙',
                'show_countdown'  => false,
                'priority'        => 83,
                'is_active'       => true,
                'is_islamic'      => true,
                'hijri_month'     => 9,
                'hijri_day'       => 1,
                'hijri_duration'  => 30,
            ],
            [
                'name'            => 'Nuzulul Quran',
                'description'     => 'Malam Nuzulul Quran – 17 Ramadan 1447 H',
                'start_month'     => 3, 'start_day' => 5,
                'end_month'       => 3, 'end_day'   => 7,
                'primary_color'   => '#0d2137',
                'secondary_color' => '#d4af37',
                'accent_color'    => '#a8d8a8',
                'css_class'       => 'theme-nuzulul-quran',
                'banner_text'     => '📖 Malam Nuzulul Quran – 17 Ramadan 1447 H',
                'banner_subtext'  => 'Memperingati turunnya Al-Quran sebagai petunjuk bagi seluruh umat manusia',
                'banner_icon'     => 'bi bi-book-fill',
                'emoji'           => '📖',
                'show_countdown'  => false,
                'priority'        => 88,
                'is_active'       => true,
                'is_islamic'      => true,
                'hijri_month'     => 9,
                'hijri_day'       => 17,
                'hijri_duration'  => 3,
            ],
            [
                'name'            => 'Idul Fitri',
                'description'     => 'Hari Raya Idul Fitri 1 Syawal 1447 H – Lebaran',
                'start_month'     => 3, 'start_day' => 20,
                'end_month'       => 3, 'end_day'   => 27,
                'primary_color'   => '#145a32',
                'secondary_color' => '#f7c948',
                'accent_color'    => '#ffffff',
                'css_class'       => 'theme-idul-fitri',
                'banner_text'     => '🌙 Selamat Hari Raya Idul Fitri 1447 H',
                'banner_subtext'  => 'Minal Aidin Wal Faizin – Mohon Maaf Lahir & Batin 🙏',
                'banner_icon'     => 'bi bi-stars',
                'emoji'           => '🌙',
                'show_countdown'  => false,
                'priority'        => 92,
                'is_active'       => true,
                'is_islamic'      => true,
                'hijri_month'     => 10,
                'hijri_day'       => 1,
                'hijri_duration'  => 8,
            ],
            [
                'name'            => 'Idul Adha',
                'description'     => 'Hari Raya Idul Adha – 10 Dzulhijjah 1447 H',
                'start_month'     => 5, 'start_day' => 27,
                'end_month'       => 6, 'end_day'   => 3,
                'primary_color'   => '#7b2d00',
                'secondary_color' => '#d4a017',
                'accent_color'    => '#fff8e7',
                'css_class'       => 'theme-idul-adha',
                'banner_text'     => '🐑 Selamat Hari Raya Idul Adha 1447 H',
                'banner_subtext'  => '10 Dzulhijjah – Semangat berkorban dan berbagi sesama 🕌',
                'banner_icon'     => 'bi bi-moon-fill',
                'emoji'           => '🐑',
                'show_countdown'  => false,
                'priority'        => 91,
                'is_active'       => true,
                'is_islamic'      => true,
                'hijri_month'     => 12,
                'hijri_day'       => 10,
                'hijri_duration'  => 8,
            ],
            [
                'name'            => 'Tahun Baru Islam',
                'description'     => 'Tahun Baru Islam – 1 Muharram 1448 H',
                'start_month'     => 6, 'start_day' => 16,
                'end_month'       => 6, 'end_day'   => 18,
                'primary_color'   => '#2c3e50',
                'secondary_color' => '#c0a060',
                'accent_color'    => '#e8d9b5',
                'css_class'       => 'theme-tahun-baru-islam',
                'banner_text'     => '🌙 Selamat Tahun Baru Islam 1448 H',
                'banner_subtext'  => '1 Muharram – Semoga tahun baru membawa keberkahan dan kebaikan',
                'banner_icon'     => 'bi bi-moon-stars',
                'emoji'           => '🌙',
                'show_countdown'  => false,
                'priority'        => 84,
                'is_active'       => true,
                'is_islamic'      => true,
                'hijri_month'     => 1,
                'hijri_day'       => 1,
                'hijri_duration'  => 3,
            ],
            [
                'name'            => 'Maulid Nabi Muhammad SAW',
                'description'     => 'Hari Kelahiran Nabi Muhammad SAW – 12 Rabiul Awal 1448 H',
                'start_month'     => 8, 'start_day' => 25,
                'end_month'       => 8, 'end_day'   => 27,
                'primary_color'   => '#0b4d2e',
                'secondary_color' => '#c9a44c',
                'accent_color'    => '#f5f0e8',
                'css_class'       => 'theme-maulid-nabi',
                'banner_text'     => '🌹 Selamat Memperingati Maulid Nabi Muhammad SAW 1448 H',
                'banner_subtext'  => '12 Rabiul Awal – Shalawat dan salam atas junjungan kita Nabi Muhammad SAW',
                'banner_icon'     => 'bi bi-flower1',
                'emoji'           => '🌹',
                'show_countdown'  => false,
                'priority'        => 86,
                'is_active'       => true,
                'is_islamic'      => true,
                'hijri_month'     => 3,
                'hijri_day'       => 12,
                'hijri_duration'  => 3,
            ],
        ];

        foreach ($themes as $theme) {
            EventTheme::updateOrCreate(
                ['css_class' => $theme['css_class']],
                $theme
            );
        }

        EventTheme::flushCache();
    }
}
