version: '3.8'
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana_separate
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=StemanGrafana2026!
      - GF_SERVER_ROOT_URL=https://admin.alumni-steman.my.id/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_SERVER_PROTOCOL=http
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./docker/grafana/provisioning:/etc/grafana/provisioning:ro
    networks:
      - grafana-network
volumes:
  grafana_data:
    name: grafana_separate_data
networks:
  grafana-network:
    driver: bridge
